# -*- coding: utf-8 -*-
"""Reto2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h9U69hL8V8q-5MsQSzptLRuOK1l8urzs
"""

aseo_lista = "XNOPUHTK" 
belleza_lista = "UTXFPGN" 
total_venta = "XNOPUHTKFG"

acumulador_aseo = 0
acumulador_belleza = 0

aseo_lista = input()
belleza_lista = input()
total_venta = input()

for producto_v in total_venta: #XNO
  if (producto_v in aseo_lista): #OUXYTU
    acumulador_aseo+=1
  if (producto_v in belleza_lista):
    acumulador_belleza+=1

  if (acumulador_aseo == acumulador_belleza):
    print("E", end="")
  elif (acumulador_aseo > acumulador_belleza):
    print("A", end="")
  elif (acumulador_aseo < acumulador_belleza):
    print("B", end="")